"""
Regression test for the Laue integrator against Precognition.

Two DHFR diffraction patterns are downloaded from SBGrid (dataset 1117), fed
through ``laue.integrate`` using version-controlled refined geometry and
predictions, and the resulting intensities are correlated against a
version-controlled table of Precognition intensities for the same two images.

The raw images (~29 MB each) are *not* version controlled; they are fetched at
test time. Only the stills experiment file, the predicted reflection table, the
detector mask (gzipped) and the Precognition reference table live in the
repository. If SBGrid cannot be reached the test is marked xfail rather than
failing outright, per the review discussion on PR #86.

The predicted reflection table was generated by ``laue.predict``, which uses the
detector mask (``pixels.mask``) to discard predictions landing in masked regions
of the detector. The mask is therefore shipped alongside the fixtures so the
prediction step is reproducible; ``laue.integrate`` itself does not read it, so
it does not affect the correlation computed here. See ``tests/data/regression/
README.md`` for the full provenance of every fixture.
"""

import gzip
import json
import os
import shutil
import subprocess

import numpy as np
import pytest

# SBGrid dataset 1117 (DHFR Laue), served from the dataset root over rsync.
SBGRID_RSYNC_ROOT = "rsync://data.sbgrid.org/10.15785/SBGRID/1117"
IMAGES = ("e080_001.mccd", "e080_002.mccd")

# Baseline established on this branch is Pearson CC ~= 0.978 over ~2200 matched
# reflections. Thresholds are set below the baseline with margin for numerical
# variation, so only a genuine regression trips them.
MIN_PEARSON_CC = 0.95
MIN_MATCHED_REFLECTIONS = 1500

DATA_DIR = os.path.join(os.path.dirname(__file__), os.pardir, "data", "regression")
EXPT_FIXTURE = os.path.join(DATA_DIR, "poly_refined_2img.expt")
REFL_FIXTURE = os.path.join(DATA_DIR, "predicted_2img.refl")
PRECOG_REFERENCE = os.path.join(DATA_DIR, "precog_reference_2img.mtz")
MASK_FIXTURE_GZ = os.path.join(DATA_DIR, "pixels.mask.gz")


def _download_images(dest_dir):
    """
    Fetch the DHFR test images from SBGrid via rsync into ``dest_dir``.

    Marks the test xfail (rather than failing) if rsync is unavailable or the
    server cannot be reached, so offline environments do not report a failure.
    """
    if shutil.which("rsync") is None:
        pytest.xfail("rsync is not available; cannot download SBGrid images.")

    for name in IMAGES:
        url = f"{SBGRID_RSYNC_ROOT}/{name}"
        try:
            subprocess.run(
                ["rsync", "-a", "--timeout=120", url, dest_dir],
                check=True,
                capture_output=True,
                timeout=600,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as e:
            pytest.xfail(f"SBGrid unreachable while downloading {name}: {e}")

        if not os.path.exists(os.path.join(dest_dir, name)):
            pytest.xfail(f"SBGrid download did not produce {name}.")


def _relocate_experiments(image_dir, out_path):
    """
    Rewrite the version-controlled experiment file so its imagesets point at the
    freshly downloaded images in ``image_dir`` and at the decompressed detector
    mask (written next to ``out_path``), then write it to ``out_path``.

    The mask is shipped gzipped and expanded here because dxtbx expects an
    uncompressed pickle. ``laue.integrate`` does not consult the mask, but
    pointing at a real file keeps the relocated experiment self-consistent and
    reproducible by ``laue.predict``.
    """
    mask_path = os.path.join(os.path.dirname(out_path), "pixels.mask")
    with gzip.open(MASK_FIXTURE_GZ, "rb") as src, open(mask_path, "wb") as dst:
        shutil.copyfileobj(src, dst)

    with open(EXPT_FIXTURE) as f:
        expt = json.load(f)
    for imageset in expt["imageset"]:
        imageset["images"] = [
            os.path.join(image_dir, os.path.basename(img)) for img in imageset["images"]
        ]
        if imageset.get("mask"):
            imageset["mask"] = mask_path
    with open(out_path, "w") as f:
        json.dump(expt, f)


def _pearson_cc_vs_precog(integrated_mtz):
    """
    Merge the integrated intensities with the Precognition reference on
    (H, K, L, BATCH) and return (pearson_cc, n_matched).
    """
    import reciprocalspaceship as rs

    dials = rs.read_mtz(integrated_mtz).reset_index()
    precog = rs.read_mtz(PRECOG_REFERENCE).reset_index()

    merged = dials.merge(precog, on=["H", "K", "L", "BATCH"], suffixes=("_d", "_p"))
    i_dials = merged["I_d"].to_numpy(dtype=float)
    i_precog = merged["I_p"].to_numpy(dtype=float)
    good = np.isfinite(i_dials) & np.isfinite(i_precog)
    i_dials, i_precog = i_dials[good], i_precog[good]

    if len(i_dials) < 2:
        return float("nan"), len(i_dials)
    return float(np.corrcoef(i_dials, i_precog)[0, 1]), len(i_dials)


@pytest.mark.regression
def test_integrate_matches_precognition(tmp_path):
    from laue_dials.command_line.integrate import run as integrate_run

    image_dir = tmp_path / "images"
    image_dir.mkdir()
    _download_images(str(image_dir))

    reloc_expt = tmp_path / "relocated.expt"
    _relocate_experiments(str(image_dir), str(reloc_expt))

    integrated_mtz = tmp_path / "integrated.mtz"
    integrate_run(
        [
            str(reloc_expt),
            str(REFL_FIXTURE),
            f"output.filename={integrated_mtz}",
            f"output.log={tmp_path / 'laue.integrate.log'}",
            "nproc=1",
        ]
    )

    assert integrated_mtz.exists(), "Integration did not produce an MTZ file."

    cc, n_matched = _pearson_cc_vs_precog(str(integrated_mtz))

    assert n_matched >= MIN_MATCHED_REFLECTIONS, (
        f"Only {n_matched} reflections matched Precognition "
        f"(expected >= {MIN_MATCHED_REFLECTIONS}); integration likely regressed."
    )
    assert cc >= MIN_PEARSON_CC, (
        f"Pearson CC vs Precognition is {cc:.4f}, below the regression "
        f"threshold of {MIN_PEARSON_CC}."
    )
